Revert "wifi: ath9k: htc_hst: free skb in ath9k_htc_rx_msg() if there is no callback function"
This reverts commit 564bc2222bf50eb6cdee715a5431bf4dc9f923c1.

log:
../drivers/net/wireless/ath/ath9k/htc_hst.c:476:9: error: use of undeclared label 'invalid'
                        goto invalid;
                             ^
1 error generated.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Ie4139202ba91faab323177251bc12c9e95e38446